# IO errors
ERR_IO_INVALID_SUPERVISION_ENGINE = (101, "INVALID_IO_ENGINE")
ERR_IO_OPERATION_NOT_SUPPORTED_BY_DRIVER = (102, "OPERATION_NOT_SUPPORTED_BY_DRIVER")
ERR_IO_INVALID_PATH = (103, "INVALID_PATH")

# Matching errors
ERR_MATCHING_MATCH_COUNT_OUT_OF_BOUNDS = (201, "MATCH_COUNT_OUT_OF_BOUNDS")

# Supervision errors
ERR_SUPERVISION_CORRESPONDENCE_NOT_FOUND = (301, "CORRESPONDENCE_NOT_FOUND")

# Template errors
ERR_TEMPLATE_INVALID_KEYPOINT = (401, "INVALID_KEYPOINT")
ERR_TEMPLATE_INVALID_SUPERVISION_ENGINE = (402, "INVALID_SUPERVISION_ENGINE")
ERR_TEMPLATE_INVALID_MATCHING_ENGINE = (403, "INVALID_MATCHING_ENGINE")
ERR_TEMPLATE_ID_NOT_UNIQUE = (404, "ID_NOT_UNIQUE")
